name: CI

permissions:
  contents: read

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@c7450ba673e133f5ee30098b3b54f444d3a2ca2d # v1.8.0

      - name: Show Forge version
        run: forge --version

      - name: Install dependencies
        run: |
          forge install foundry-rs/forge-std@v1.12.0
          forge install OpenZeppelin/openzeppelin-contracts@v5.5.0

      - name: Run Forge fmt
        continue-on-error: true
        run: forge fmt --check

      - name: Run Forge build
        run: forge build --sizes

      - name: Run Forge tests
        run: forge test -vvv
